### ISSUE TITLE
Reconsider module name

### ISSUE THREAD

**Issue by marschall** [javaee/jsonp#43]
The current module name is `java.json` while the package name is `javax.json`. Stephen Colebourne has [argued](http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) that the module name should be the same as the name of the super-package.

I find it very dangerous to settle for a module name without any guidance from the EE expert group on a naming convention. You won't be able to change the module name without breaking users.

I think we can all agree that the [current situation](https://glassfish.java.net/wiki-archive/Java%20EE%207%20Maven%20Coordinates.html) regarding Maven coordinates is suboptimal and we would like to avoid this for Java (EE) 9.

**Comment by m0mus** [comment]
It was already discussed on JSON-P mailing list.

Look here:
http://openjdk.java.net/jeps/200

It says:
"Standard modules, whose specifications are governed by the JCP, must have names starting with the string 'java.'."

I see no problems here. Java EE 8 doesn't define any module name rules because it's not designed to work with JDK9. If next Java EE version defines different module naming conventions we will change it in the corresponding version of JSON-P.

**Comment by marschall** [comment]
> If next Java EE version defines different module naming conventions we will change it in the corresponding version of JSON-P.

That will transitively break everybody who has written a module against JSON-P in the mean time.

**Comment by keilw** [comment]
While I understand Stephen's concerns, it looks like the OpenJDK architects and Spec Lead does not agree with him on that. It was subsequently changed in the JDK and http://openjdk.java.net/jeps/200 states the module name naming guidelines. 

The umbrella Java EE Spec Leads made clear, they won't define anything prior to Java EE 9, so unless there's any other coordinated naming effort I would stick to http://openjdk.java.net/jeps/200 for now.

@marschall I asked Bill and Linda the same thing (in the JPA and Umbrella Java EE list, if migrated to groups.io you may find it there, but I don't know if those lists were ever migrated from java.net) and they/he said, it is currently up to individual JSRs and subject to change with EE 9.

**Comment by m0mus** [comment]
I suppose that this issue has been answered by my and @keilw comments. Closing it.
