### ISSUE TITLE
Create GitHub tags

### ISSUE THREAD

**Issue by keilw** [javaee/jsonp#48]
At least https://github.com/javaee/glassfish already has tags like:
- javaee7
- javaee
- glassfish
- javaee8

Could a few of those (like "javaee") and others especially "json" also be applied to this repository?

**Comment by heavyvinicio** [comment]
Hi, I could help with this topic. However, you must add topics to the repository, which must be added to the project manager, or at least, only that way I know.

**Comment by m0mus** [comment]
I added some labels, a bit more than @keilw suggested. :)
If everybody is happy, I'll close this issue.

**Comment by heavyvinicio** [comment]
Great work!! :)

**Comment by keilw** [comment]
Looks good to me.

**Comment by m0mus** [comment]
Great! I am glad that you like it, folks! Closing the issue...
