### ISSUE TITLE
Spec License in JavaDoc not accessible from javadoc.io

### ISSUE THREAD

**Issue by keilw** [javaee/jsonp#50]
On https://javadoc.io/doc/javax.json/javax.json-api/1.1
The URL https://static.javadoc.io/javax.json/javax.json-api/1.1/doc-files/speclicense.html
in the bottom of JavaDocs leads to an error page:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4187E02FCAA870F5</RequestId>
<HostId>
rx+8/t/L/Pm3koPr5zzD64XSnjITZYo6MhMD8YA/40rWBTzwGoyl1orSQJ2QEFfm9ZmPUWOclEg=
</HostId>
</Error>
```

**Comment by m0mus** [comment]
Fixed by 59cd1f30a8e6b438aaa021408bef323313d9f26e

**Comment by keilw** [comment]
Thanks, will it automatically propagate to JavaDoc.io at some point?

**Comment by m0mus** [comment]
On next release

**Comment by keilw** [comment]
Of the actual JSR? or does the JavaDoc get released there by code changes like a CI system?

**Comment by m0mus** [comment]
It is impossible to release javadoc without releasing a project. It's also not possible to change already released version. If you know the solution, let me know, we will do it.

**Comment by keilw** [comment]
If this JavaDoc site only picks up on a new version, then I'm afraid it might have to wait for either a MR or new JSR. I am not the legal or license expert to tell if it's a problem. If you know nobody at Oracle who has a problem with it, guess it can wait till something severe came up to consider a MR (maybe towards JDK 9 support?;-)
