### ISSUE TITLE
Did not have a method to get number like "21.22" from json string though JsonObject

### ISSUE THREAD

**Issue by gaoqiang0306** [javaee/jsonp#54]
{
            "UnitOfMeasure": "MMO",
            "UnitOfMeasureTo": "MDY",
            "ConversionRate": 22.012,
            "EnabledFlag": "Y"
        }
JsonObject jsonObject;
jsonObject only have getString and getInt, how to get num- double？

**Comment by keilw** [comment]
Yes, you get it as a `JsonNumber` or `VALUE_NUMBER` event using the streaming `JsonParser`, see https://javaee.github.io/jsonp/getting-started.html for examples.
I cannot tell what your UnitOfMeasure in this case stands for, but if you want more detailed UoM interpretation from JSON strings, please have a look at https://github.com/unitsofmeasurement/jackson-module-unitsofmeasure. We don't use JSON-B there yet, but would be happy to migrate it soon, especially if a concrete use case exists.

**Comment by gaoqiang0306** [comment]
hi @keilw ，
Thanks for your help, i can get the 22.012 as a BigDecimal through JsonParser now. it's a little different from org.json jar i used before, it had had getLong, getBigDecimal, getDouble, from JSONObject, so it's confused to me when using javax.json. 
But ok, now, i knew how to use it.
Regards,
Qiang

**Comment by m0mus** [comment]
Closing it, because the question is answered.
