### ISSUE TITLE
Reference impl does not contain META-INF/services/javax.json.spi.JsonProvider

### ISSUE THREAD

**Issue by aguibert** [javaee/jsonp#55]
I'm currently working on implementation of some JSON-P 1.1 integration code and hit a block because the ref impl does not include any META-INF/services/ file to indicate that it provides an implementation of javax.json.spi.JsonProvider.

This is not a new issue (JSON-P 1.0 doesn't have META-INF/services/ either) but I was wondering if there is a technical reason behind this quirk?

**Comment by keilw** [comment]
https://github.com/javaee/jsonp/blob/master/api/src/main/java/javax/json/spi/JsonProvider.java uses Class.forName(DEFAULT_PROVIDER) with the name of the Glassfish RI element.  So if no META-INF/services is provided, the fall-back will try to instanciate the Glassfish class (and that usually works, as long as you got both in the classpath of course) I have only used the RI so far, many large vendors use it, I don't recall Red Hat or IBM using their own, but Apache Jenson should be proof enough, that other implementations must be discovered correctly if available.

**Comment by aguibert** [comment]
@keilw Yes, the RI will fall back to class.forName if an attempt is made to load a provider.  However, I'm operating in an OSGI and trying to specify a service dependency on the `javax.json.spi.JsonProvider`.  This works fine when I use an alternate impl such as Apache Johnzon, but it fails when I use the reference impl because the reference impl does not declare that it provides this service and therefore there is no `javax.json.spi.JsonProvider` in the service registry when just the JSONP ref impl is being used.

**Comment by aguibert** [comment]
for reference, the JSON-B 1.0 default impl (Eclipse Yasson) does provide a META-INF/service/, which is what I am also expecting with JSON-P 1.1

**Comment by keilw** [comment]
Yasson was created from scratch and had an Eclipse RI. Quite likely something like OSGi was also considered a higher priority or naturally came with running at Eclipse. Although both have the same Spec Lead now, that doesn't mean Oracle/the Spec Lead rewrote everything from scratch. I know we also use something with priorities in JSRs 354 or 363 but the prior Spec Lead who worked on 1.0 probably more or less by himself did it differently. It works, and does so since 1.0. If there's really a major issue with OSGi or (that could be a more compelling reason for Oracle) Java 9/Jigsaw, there would be an option of a MR at some point, but 1.1 as it stands now is Final (just like JSON-B) 

Why is Glassfish/RI not in the classpath when you use OSGi? If it was (e.g. declared in your META-INF, etc. dependencies) I don't see why the fallback should fail.

**Comment by aguibert** [comment]
For my product (WebSphere Liberty) we do not use a classpath for our server runtime, and instead rely on the OSGi service registry.  

I agree that our hands are tied on making a JSON-P 1.1 API change since the spec is now final, but perhaps we could we include the META-INF/service/ file in an MR of the Glassfish/RI without a spec API  update?

Additionally, I think we will hit a similar issue on Java 9 because the Glassfish/RI's [module-info.java](https://github.com/javaee/jsonp/blob/master/impl/src/main/jdk9/module-info.java) declares that it  `uses javax.json.spi.JsonProvider` and instead should declare that it `provides javax.json.spi.JsonProvider with org.glassfish.json.JsonProviderImpl`.

**Comment by keilw** [comment]
If you can reproduce this as a problem for all of Liberty, please consider a more OSGi-driven description and maybe do a new issue. JSON-P among other usages is one of the cornerstones to Eclipse MicroProfile, so I bet not just IBM will use it there (but not many use OSGi under the hood ;-)

**Comment by lukasj** [comment]
Note that the jar as it is now is all-in-one bundle, so the impl is there, within same code source, loaded by same classloader as the serviceloader. What would be the benefit of doing service lookup over current fallback to newInstance () in this case?

**Comment by aguibert** [comment]
@lukasj In my case we have the app server providing the spec API, and the user may plug in their own spec-compliant JSON-P implementation, which requires the presence of the META-INF/service/.  In this scenario, we would have the API and impl being provided by separate bundles/classloaders and they would still link together using the standard ServiceLoader mechanism.

The all-in-one API+RI bundle is convenient, but I'm surprised that the RI is not provided independently.
